# This role binding allows "matt", "jaya" to write (create/update) pods in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: write-pods
  namespace: default
  labels:
    env: dev
subjects:
#- kind: User
#  name: matt # Name is case sensitive
#  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: james # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: jaya # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-writer # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io